-- =====================================================================
-- 0024  Interest: a price for time and money, not a price for a service
-- =====================================================================
--
-- The other half of the accrual ladder. 0020 built a MONTHLY PLATFORM FEE
-- accrued daily and deliberately did not build interest, for a reason it
-- wrote down and named the missing accounts for (docs/ACCRUAL.md §7):
--
--   "4200 Fee income is what we CHARGE, and interest priced on a balance
--    and a number of days is not a fee for a service."
--
-- This migration adds the two accounts 0020 named -- 4400 Interest income
-- (overdraft) and 5400 Interest expense (credit balances) -- and the
-- daily accrual that posts to them.
--
-- ---------------------------------------------------------------------
-- 1.  WHAT THE BOOK ACTUALLY SHOWS, MEASURED RATHER THAN ASSUMED
-- ---------------------------------------------------------------------
--
-- 0020's author was told the book had overdrawn accounts and corrected
-- the premise: v_overdrawn_accounts returned zero rows. That correction
-- was re-measured before this file was written, at the current booking
-- watermark, and it still holds -- and more strongly than before:
--
--   * v_overdrawn_accounts:                                     0 rows
--   * every deposit leaf, settled balance today:              all > 0
--   * every deposit leaf, settled balance on EVERY value date
--     in the 45-day catch-up window:                          all > 0
--   * every account in the chart, natural balance < 0:          0 rows
--
-- So OVERDRAFT INTEREST SHIPS WITH ZERO ROWS TODAY, and this file says
-- so rather than manufacturing an overdraft to photograph. What ships
-- with rows is CREDIT INTEREST -- what we pay a customer for holding a
-- balance with us -- on four real deposit accounts.
--
-- Both sides are built, because they are not two products. A business
-- current account has a credit rate and an arranged-overdraft rate, and
-- WHICH ONE APPLIES ON A GIVEN DAY IS DECIDED BY THE SIGN OF THE BALANCE
-- ON THAT DAY, not by which product the customer bought. One enrolment,
-- one rate card, two sides. The day an account crosses zero, the same
-- schedule prices the day before on 5400 and the day after on 4400, and
-- nothing has to be reconfigured for that to happen.
--
-- ---------------------------------------------------------------------
-- 2.  WHY THIS IS NOT accrual_product = 'interest' ON 0020's TABLES
-- ---------------------------------------------------------------------
--
-- docs/ACCRUAL.md §7 sketched the extension as
--
--   "an ALTER TYPE accrual_product ADD VALUE 'overdraft_interest', a
--    rate_bps column beside monthly_cents..."
--
-- That was tried first, against this database, and it cannot be done in
-- one migration. Measured, not assumed:
--
--   postgres=# BEGIN;
--   postgres=# ALTER TYPE accrual_product ADD VALUE 'interest';
--   postgres=# SELECT 'interest'::accrual_product;
--   ERROR:  unsafe use of new value "interest" of enum type accrual_product
--
-- PostgreSQL 18.6, and the restriction is documented and permanent: an
-- enum value added by ALTER TYPE cannot be USED until the adding
-- transaction commits. scripts/migrate.mjs applies each file inside one
-- transaction -- correctly, because a half-applied migration is worse
-- than a refused one -- so a single migration can add the value or use
-- it, never both. Splitting across 0024 and 0025 was not available
-- either: this work owns one migration number.
--
-- The second reason is better than the first. `accrual_posting` carries
-- SEVEN stored relations re-derived by `accrual_posting_arithmetic`, and
-- `assert_accrual_posting()` asserts the entry is exactly two lines, a
-- debit to the deposit account and a credit to 4200. Every one of those
-- is fee-shaped. Making them hold interest too would mean nullable
-- columns, a CHECK that branches, and a lifecycle trigger with two arms
-- -- weakening a working proof to avoid writing a second one. So 0020's
-- objects are NOT TOUCHED BY THIS FILE. Nothing here alters a table,
-- replaces a view, or drops a constraint that 0020 created.
--
-- What IS reused is the machinery, which is the thing that mattered:
--
--   * the unit is the (schedule, date) pair          -- 0020 §3
--   * the claim is a UNIQUE row                      -- interest_day
--   * the idempotency key is GENERATED by Postgres
--     from the two source facts                      -- never by the job
--   * the key goes to postEntry(), where
--     journal_entry.idempotency_key is UNIQUE        -- 0001 §12
--   * the row lock is a SECURITY DEFINER function    -- 0008/0012/0020
--   * which dates are owed is ONE SQL function       -- no date maths in TS
--   * the arithmetic is stored AND re-derived by a CHECK
--
-- and, above all, THE SAME TICK. `runAccrual()` runs the fee leg and
-- then the interest leg in one invocation of `/api/cron/accrual`. There
-- is no second scheduler, no second endpoint and no second cron entry.
--
-- The fee leg runs FIRST, deliberately: the fee is a debit dated D, so
-- the end-of-day-D balance that interest is priced on includes it. The
-- ordering is stated because it is observable -- reversing it would move
-- the basis by the fee, which is under a cent of interest but is not
-- nothing, and an ordering that matters should be written down rather
-- than inherited from a loop.
--
-- ---------------------------------------------------------------------
-- 3.  THE ROUNDING RULE: DESIGN §12.2, AND WHY IT IS NOT §12.3
-- ---------------------------------------------------------------------
--
-- research/ledger/DESIGN.md §12 has two rules and the whole skill is
-- knowing which applies:
--
--   §12.2  ONE value -> ONE cent amount:  round HALF TO EVEN.
--   §12.3  ONE amount split across N shares: LARGEST REMAINDER.
--
-- 0020 argued, correctly, that a monthly fee accrued daily is §12.3: the
-- month has a total -- the quoted price -- and the days are shares of
-- it, so the shares must add back up to it exactly, and rounding each
-- day independently bills $24.90 for a $25.00 plan.
--
-- DAILY INTEREST IS §12.2, and the reason is not a preference. §12.3 is
-- not merely worse here, IT IS UNDEFINED: largest-remainder needs a
-- SOURCE AMOUNT to distribute, and daily interest has none. There is no
-- month-total to allocate, because the balance changes every day and the
-- month's interest is not known until the month has happened. You cannot
-- floor N shares of a number you do not have.
--
-- What daily interest IS, exactly, is one value -- a balance, a rate and
-- one day -- becoming one cent amount. That is §12.2's sentence with no
-- interpretation required.
--
--     amount = round_half_even( |balance| * rate_bps / (10000 * 365) )
--
-- HALF TO EVEN AND NOT HALF UP, for §12.2's own stated reason: "half-up
-- biases every tie in one direction, and over a year of interchange that
-- bias is a real number." Here the tie is the half-cent, and half-up
-- would hand it to the same party every time -- to us on an overdraft,
-- to the customer on a credit balance -- forever.
--
-- ROUNDING IS SYMMETRIC IN THE SIGN. The magnitude is rounded and the
-- side is carried separately (interest_side_of), rather than rounding a
-- signed number. Floor division on a negative basis would round every
-- overdraft charge AWAY from zero and every credit payment TOWARD it --
-- a systematic bias in the bank's favour that no line of code would have
-- to state out loud. |balance| is rounded; the sign picks the account.
--
-- NOBODY EATS A RESIDUAL PENNY HERE, AND THAT IS NOT A CONTRADICTION.
-- §12.3's residual is a real penny that must land SOMEWHERE, because the
-- shares have to sum to a source. §12.2 has no residual to place: the
-- sub-cent fraction never existed as money, no party was ever credited
-- with it, and the entry is two equal and opposite lines summing to
-- zero. This is also why §12.6's dust clearing (2900) is NOT engaged --
-- 2900 exists for dust that arrived as a real external amount, such as a
-- USDC transfer with six decimals, where truncating would break the
-- identity between customer balances and our obligation. A fraction of a
-- cent of interest is not money that arrived; it is precision that was
-- never claimed. The bound is half a cent per account per day, it is
-- unbiased by construction, and it is disclosed.
--
-- The residual penny placed ACROSS DAYS is 0020's, and it stays 0020's.
-- There are still exactly two rounding rules in this ledger, they are
-- the two DESIGN §12 already had, and each accrual product uses the one
-- whose precondition it actually meets.
--
-- ---------------------------------------------------------------------
-- 4.  DAY COUNT: ACT/365 FIXED, AND WHY IT IS DEFENSIBLE
-- ---------------------------------------------------------------------
--
-- A rate is per annum; a day is a fraction of a year; the convention is
-- which fraction. Stated, because "the usual one" is not an answer.
--
-- ACT/365 FIXED: the numerator is the actual number of days (here always
-- 1 -- this is a DAILY accrual, so each posting is one day) and the
-- denominator is 365, in every year, leap or not.
--
--   * It is the US deposit convention. 12 CFR 1030 (Reg DD) Appendix A
--     computes the daily periodic rate as the nominal annual rate
--     divided by 365. A deposit product whose disclosed APY is computed
--     on /365 and whose ledger accrues on /360 discloses one number and
--     charges another.
--
--   * ACT/360 -- the money-market and commercial-lending convention --
--     pays and charges 365/360 = 1.389% MORE per year for the same
--     quoted rate. That is defensible on a commercial loan quoted that
--     way and indefensible on a consumer-facing deposit disclosure. We
--     are a business current account and both sides are disclosed, so
--     both sides get /365.
--
--   * FIXED rather than ACT/ACT: in a leap year the 366th day accrues at
--     1/365, so a leap year pays 366/365 of the nominal rate. The
--     alternative changes the denominator mid-product, which means two
--     statements a year apart divide by different numbers for no reason
--     a customer can see. The over-accrual is 0.27% of the interest, it
--     is in the customer's favour on a credit balance and against them
--     on an overdraft, and it is written down here.
--
-- The denominator is a COLUMN on the rate policy, not a constant, so the
-- convention is data that a row can state and a reviewer can read --
-- constrained to (360, 365) so it cannot become a typo.
--
-- ---------------------------------------------------------------------
-- 5.  RATES ARE CONFIGURATION, EFFECTIVE-DATED, AND CANNOT REACH BACK
-- ---------------------------------------------------------------------
--
-- `approval_policy` (0001 §12) and `funds_availability_policy` (0001 §5)
-- are the pattern: a policy is a fact with a lifespan, it lives in its
-- own versioned table, it is append-only, and a change is a NEW ROW with
-- a later effective_from. `interest_rate_policy` is the third of them
-- and is built the same way, with one addition those two do not have.
--
-- THE ADDITION: a new policy row's effective_from must be strictly
-- LATER than every existing row for its tier AND strictly later than
-- every date already accrued under it. So "a rate change must not
-- retroactively re-price yesterday" is not a convention that a careful
-- operator observes -- it is a trigger that refuses the INSERT.
--
-- Resolution is `the greatest effective_from <= the accrual date`, so a
-- day accrued last week resolves to last week's rate forever, including
-- when the tick replays that date. `v_interest_rate_drift` asks the same
-- question of every posting already on the book and must return zero
-- rows; it is the invariant that would catch a policy row inserted
-- behind the trigger's back.
--
-- THE RATE IS ON THE RATE CARD, NOT ON THE ENROLMENT. A schedule cites a
-- TIER ('standard'), not a rate. One new policy row re-prices every
-- enrolled account from a date forward; putting the rate on the schedule
-- would mean N new schedule rows per rate change and N chances to write
-- a different number on one of them.
--
-- ---------------------------------------------------------------------
-- 6.  THE BASIS IS THE SETTLED LEDGER BALANCE, AT A RECORDED WATERMARK
-- ---------------------------------------------------------------------
--
-- Interest is priced on `ledger_settled_cents(account, accrual_date,
-- observed_booking_seq)` from 0022 -- THE canonical bitemporal balance
-- in this system, not a fourth private copy of one. Both predicates are
-- load-bearing:
--
--   value_date  <= the accrual date    what the ledger says about that
--                                      business day
--   booking_seq <= the watermark       what we had LEARNED when we
--                                      priced it
--
-- Not the AVAILABLE balance. Available subtracts holds, and a hold is
-- money we have not yet been asked for -- the customer still holds the
-- funds and we still owe them, so we still owe interest on them. A card
-- authorisation is not a withdrawal.
--
-- THE WATERMARK IS STORED, and that is a bitemporal decision with a
-- consequence. A correction backdated into a day that has already been
-- priced does NOT re-price that day: the posting stands, the row records
-- exactly which watermark it was priced at, and the number remains
-- reproducible from the row. Re-pricing would mean reversing and
-- re-booking an interest charge that was correct on the information
-- available -- which is a real product (an interest adjustment) and is
-- named as a gap in docs/ACCRUAL.md rather than half-built here.
--
-- `assert_interest_posting()` RE-DERIVES THE BASIS from the account, the
-- date and the stored watermark and refuses a row that disagrees, so the
-- balance on the row is not trusted either. TypeScript computes,
-- Postgres verifies -- 0020's bargain, kept.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 7.  The two accounts docs/ACCRUAL.md §7 named
-- ---------------------------------------------------------------------
--
-- src/lib/ledger/chart.ts carries the same two rows with the same names
-- and the same `why`; scripts/seed.mjs inserts the chart from that array
-- on a fresh database. This INSERT is for the database that already
-- exists and has already been seeded, and it is written as INSERT ...
-- SELECT over the entities that are actually there, so on a fresh
-- database (where the seed has not run and no entity exists) it inserts
-- nothing and the seed creates them instead. Both paths converge on one
-- row per entity, and ON CONFLICT DO NOTHING means neither can double.

INSERT INTO account (entity_id, code, name, parent_id, type, book,
                     currency, business_id, rail_control, is_postable)
SELECT p.entity_id, '4400', 'Interest income — overdraft', p.id,
       'income', 'financial', 'USD', NULL, NULL, true
  FROM account p
 WHERE p.code = '4000' AND p.business_id IS NULL
ON CONFLICT DO NOTHING;

INSERT INTO account (entity_id, code, name, parent_id, type, book,
                     currency, business_id, rail_control, is_postable)
SELECT p.entity_id, '5400', 'Interest expense — credit balances', p.id,
       'expense', 'financial', 'USD', NULL, NULL, true
  FROM account p
 WHERE p.code = '5000' AND p.business_id IS NULL
ON CONFLICT DO NOTHING;


-- ---------------------------------------------------------------------
-- 8.  Vocabulary
-- ---------------------------------------------------------------------

-- WHICH SIDE OF THE BOOK TODAY LANDS ON, derived from the sign of the
-- balance and from nothing else. Not a product, not a customer choice,
-- not a column somebody sets: interest_side_of(balance) is a function.
--
-- 'flat' is a real state and it is not an error -- a deposit account at
-- exactly zero owes nothing and is owed nothing. It always decides
-- 'skipped', because postEntry() refuses a zero-amount line and is right
-- to.
CREATE TYPE interest_side AS ENUM ('credit', 'overdraft', 'flat');

COMMENT ON TYPE interest_side IS
  'credit = the customer is in credit and we PAY (5400 debit, deposit credit). overdraft = the customer is in debit and we CHARGE (deposit debit, 4400 credit). flat = a zero balance, which prices at nothing.';

-- WHICH WAY §12.2 WENT, recorded per posting rather than inferred later.
-- 'tie_to_even' is the only one of the four that half-up would have got
-- different, so it is the label worth being able to grep for.
CREATE TYPE interest_rounding AS ENUM ('exact', 'down', 'up', 'tie_to_even');

COMMENT ON TYPE interest_rounding IS
  'How the exact fraction became a cent amount. exact = it divided. down/up = the ordinary cases. tie_to_even = the fraction was exactly a half cent and DESIGN §12.2 broke it to the even cent -- the only case where half-up would have given a different answer.';


-- ---------------------------------------------------------------------
-- 9.  The arithmetic, as IMMUTABLE integer functions
-- ---------------------------------------------------------------------
--
-- These ARE the rounding rule. Every operand and every result is bigint
-- or a small int. There is no numeric, no float, no division that is not
-- integer division, and no intermediate that holds a fraction. IMMUTABLE
-- so a CHECK constraint may call them, which is the point: TypeScript
-- computes the same integers and the database refuses to store any other
-- answer.

-- D = 10000 * day_count. 10000 because a rate is in BASIS POINTS, which
-- is how a rate is stored integer-scaled: 150 bps is 1.50% and is the
-- integer 150, never 0.015.
CREATE FUNCTION interest_denominator(p_day_count int) RETURNS bigint
LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT 10000::bigint * p_day_count
$$;

-- N = |balance| * rate_bps. The MAGNITUDE, always >= 0 -- the sign is
-- carried by interest_side_of and applied when the entry is built, so
-- the rounding below cannot be asymmetric in the sign.
--
-- Overflow is a loud failure rather than a silent wrap: bigint tops out
-- at 9.22e18, so this raises above roughly $9.2 trillion at 100% a year.
-- A rate is CHECKed <= 10000 bps on every table that stores one, which
-- is what keeps that bound where it is.
CREATE FUNCTION interest_numerator(p_balance_cents bigint, p_rate_bps int) RETURNS bigint
LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT abs(p_balance_cents) * p_rate_bps::bigint
$$;

-- DESIGN §12.2, in five lines of integer arithmetic.
--
--   q = N div D,  r = N mod D,  both non-negative
--   2r > D  -> the fraction is past a half: round up
--   2r < D  -> short of a half: round down
--   2r = D  -> EXACTLY a half: round to the EVEN cent, i.e. up iff q is
--              odd. `q % 2` is 1 for odd q and 0 for even q, so the
--              whole tiebreak is one modulo and no branch.
--
-- Comparing 2r against D rather than r against D/2 is deliberate: D/2 on
-- integers would truncate for an odd D and would silently classify some
-- genuine ties as 'down'.
CREATE FUNCTION interest_round_half_even(p_num bigint, p_den bigint) RETURNS bigint
LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT (p_num / p_den)
       + CASE
           WHEN 2 * (p_num % p_den) > p_den THEN 1
           WHEN 2 * (p_num % p_den) < p_den THEN 0
           ELSE (p_num / p_den) % 2
         END
$$;

CREATE FUNCTION interest_rounding_of(p_num bigint, p_den bigint) RETURNS interest_rounding
LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT CASE
           WHEN p_num % p_den = 0            THEN 'exact'
           WHEN 2 * (p_num % p_den) = p_den  THEN 'tie_to_even'
           WHEN 2 * (p_num % p_den) > p_den  THEN 'up'
           ELSE 'down'
         END::interest_rounding
$$;

-- One day's interest, in cents, as a MAGNITUDE.
CREATE FUNCTION interest_daily_cents(p_balance_cents bigint, p_rate_bps int, p_day_count int)
RETURNS bigint
LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT interest_round_half_even(
           interest_numerator(p_balance_cents, p_rate_bps),
           interest_denominator(p_day_count))
$$;

CREATE FUNCTION interest_side_of(p_balance_cents bigint) RETURNS interest_side
LANGUAGE sql IMMUTABLE STRICT AS $$
  SELECT CASE
           WHEN p_balance_cents > 0 THEN 'credit'
           WHEN p_balance_cents < 0 THEN 'overdraft'
           ELSE 'flat'
         END::interest_side
$$;

COMMENT ON FUNCTION interest_round_half_even(bigint, bigint) IS
  'DESIGN §12.2 round-half-to-even on a rational N/D, in integers. The tie goes to the EVEN cent, which is the whole reason §12.2 is half-even rather than half-up: half-up would hand every half-cent to the same party forever.';
COMMENT ON FUNCTION interest_daily_cents(bigint, int, int) IS
  'One business date of interest, as a magnitude in cents: |balance| * rate_bps / (10000 * day_count), rounded half to even. The side (who pays whom) is interest_side_of(balance) and is applied when the journal entry is built.';

ALTER FUNCTION interest_denominator(int)                    SET search_path = public, pg_temp;
ALTER FUNCTION interest_numerator(bigint, int)              SET search_path = public, pg_temp;
ALTER FUNCTION interest_round_half_even(bigint, bigint)     SET search_path = public, pg_temp;
ALTER FUNCTION interest_rounding_of(bigint, bigint)         SET search_path = public, pg_temp;
ALTER FUNCTION interest_daily_cents(bigint, int, int)       SET search_path = public, pg_temp;
ALTER FUNCTION interest_side_of(bigint)                     SET search_path = public, pg_temp;


-- ---------------------------------------------------------------------
-- 10.  The rate card: a tier, and its versions
-- ---------------------------------------------------------------------

-- A named rate card. Exists so a schedule cites something the database
-- can check -- a free-text tier would let a typo enrol an account onto a
-- rate card that has no rows, and every one of its days would then fail
-- at the trigger instead of at the enrolment.
CREATE TABLE interest_rate_tier (
  tier        text PRIMARY KEY CHECK (length(btrim(tier)) > 0),
  description text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- One row per (tier, effective_from). approval_policy's shape, with the
-- two rates that a current account actually has and the day-count
-- convention stated as data.
--
-- BOTH RATES LIVE ON ONE ROW on purpose. A rate card that let the credit
-- rate change on one date and the overdraft rate on another would make
-- "what were our rates on 9 September" a question with two answers and a
-- join. One row, one date, both numbers.
CREATE TABLE interest_rate_policy (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tier                  text NOT NULL REFERENCES interest_rate_tier(tier),
  effective_from        date NOT NULL,

  -- What we PAY on a credit balance. Integer basis points, never a
  -- decimal and never a float: 150 is 1.50% a year.
  credit_rate_bps       integer NOT NULL CHECK (credit_rate_bps BETWEEN 0 AND 10000),
  -- What we CHARGE on a debit balance. Higher, and that is the product,
  -- not an accident -- an arranged business overdraft is expensive money.
  overdraft_rate_bps    integer NOT NULL CHECK (overdraft_rate_bps BETWEEN 0 AND 10000),

  -- §4. ACT/365 fixed is the default and the argued choice; 360 is
  -- permitted so that a money-market product could be priced honestly on
  -- its own convention rather than by quietly scaling a rate.
  day_count_denominator integer NOT NULL DEFAULT 365
                          CHECK (day_count_denominator IN (360, 365)),

  note                  text NOT NULL CHECK (length(btrim(note)) > 0),
  created_by            uuid NOT NULL REFERENCES actor(id),
  created_at            timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT interest_rate_policy_version UNIQUE (tier, effective_from)
);

CREATE INDEX interest_rate_policy_lookup_idx
  ON interest_rate_policy (tier, effective_from DESC);

COMMENT ON TABLE interest_rate_policy IS
  'The rate card, effective-dated and append-only. approval_policy and funds_availability_policy are the pattern; the addition here is a trigger that refuses a row which would re-price a date already accrued.';
COMMENT ON COLUMN interest_rate_policy.day_count_denominator IS
  'ACT/365 fixed by default: Reg DD Appendix A computes the daily periodic rate as the annual rate over 365. 360 would pay and charge 1.389% more a year for the same quoted rate.';


-- THE RULE THAT MAKES "A RATE CHANGE CANNOT RE-PRICE YESTERDAY" A
-- CONSTRAINT RATHER THAN A CONVENTION.
--
-- Two conditions, and the second is the one with teeth:
--
--   (a) effective_from must be later than every existing row for the
--       tier. Rates move forward. Without this, an INSERT with an older
--       date would silently become the resolved rate for a window of
--       past dates.
--
--   (b) effective_from must be later than every date already ACCRUED
--       under this tier. (a) alone is not enough: if the newest policy
--       row is from March and the tick has priced days through
--       September, a row effective in April satisfies (a) and re-prices
--       five months of postings that are already on the ledger.
--
-- Refusing the INSERT is the right remedy rather than detecting it
-- afterwards, because afterwards the postings are immutable and the only
-- repair is a reversal and a re-book of every affected day.
CREATE FUNCTION assert_interest_rate_policy() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_latest date;
  v_priced date;
BEGIN
  SELECT max(p.effective_from) INTO v_latest
    FROM interest_rate_policy p WHERE p.tier = NEW.tier;

  IF v_latest IS NOT NULL AND NEW.effective_from <= v_latest THEN
    RAISE EXCEPTION
      'tier % already has a rate effective %; a rate change is a LATER row, never an earlier or equal one',
      NEW.tier, v_latest USING ERRCODE = '55006';
  END IF;

  SELECT max(d.accrual_date) INTO v_priced
    FROM interest_day d
    JOIN interest_schedule s ON s.id = d.schedule_id
   WHERE s.rate_tier = NEW.tier;

  IF v_priced IS NOT NULL AND NEW.effective_from <= v_priced THEN
    RAISE EXCEPTION
      'tier % has already accrued through %; a rate effective % would retroactively re-price days already on the ledger',
      NEW.tier, v_priced, NEW.effective_from USING ERRCODE = '55006';
  END IF;

  RETURN NEW;
END $$;

ALTER FUNCTION assert_interest_rate_policy() SET search_path = public, pg_temp;

CREATE TRIGGER interest_rate_policy_forward_only
  BEFORE INSERT ON interest_rate_policy
  FOR EACH ROW EXECUTE FUNCTION assert_interest_rate_policy();


-- THE ONLY DEFINITION of "which rate applied on which date": the
-- greatest effective_from that is not after the date. STABLE, not
-- IMMUTABLE -- it reads a table -- so it cannot appear in a CHECK, which
-- is exactly why the posting stores the resolved policy id and a trigger
-- compares the two.
CREATE FUNCTION interest_rate_at(p_tier text, p_date date)
RETURNS interest_rate_policy
LANGUAGE sql STABLE AS $$
  SELECT p.*
    FROM interest_rate_policy p
   WHERE p.tier = p_tier
     AND p.effective_from <= p_date
   ORDER BY p.effective_from DESC
   LIMIT 1
$$;

ALTER FUNCTION interest_rate_at(text, date) SET search_path = public, pg_temp;

COMMENT ON FUNCTION interest_rate_at(text, date) IS
  'The rate card as it stood on a business date. One definition, asked by the tick, by the lifecycle trigger and by v_interest_rate_drift -- so a replay of an old date re-derives the old rate by construction rather than by care.';


-- ---------------------------------------------------------------------
-- 11.  The enrolment
-- ---------------------------------------------------------------------
--
-- One live enrolment per account, enforced by the same kind of gist
-- EXCLUDE constraint 0020 used for prices. Two overlapping enrolments
-- would each claim their own (schedule, date) pairs for the same account
-- and the same day, and the customer would be paid or charged twice with
-- both halves arithmetically perfect.
--
-- There is no product column, because there is no product choice: an
-- account is enrolled in interest, and the sign of its balance on the
-- day decides which side of the book the day lands on.

CREATE TABLE interest_schedule (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The customer's deposit account. Tenancy is reached through it -- no
  -- business_id column here to drift from account.business_id.
  account_id   uuid NOT NULL REFERENCES account(id),

  -- The rate card, not a rate. See §5.
  rate_tier    text NOT NULL REFERENCES interest_rate_tier(tier),

  currency     char(3) NOT NULL DEFAULT 'USD' CHECK (currency = 'USD'),

  start_date   date NOT NULL,
  end_date     date,

  created_by   uuid NOT NULL REFERENCES actor(id),
  created_at   timestamptz NOT NULL DEFAULT now(),

  -- Derived from the fact that caused the enrolment, so re-running the
  -- thing that creates enrolments cannot create a second one.
  schedule_key text NOT NULL UNIQUE CHECK (length(btrim(schedule_key)) > 0),

  CONSTRAINT interest_schedule_window CHECK (end_date IS NULL OR end_date >= start_date),

  CONSTRAINT interest_schedule_no_overlap EXCLUDE USING gist (
    account_id WITH =,
    daterange(start_date, COALESCE(end_date, 'infinity'::date), '[]') WITH &&
  )
);

CREATE INDEX interest_schedule_account_idx ON interest_schedule (account_id);

COMMENT ON TABLE interest_schedule IS
  'Who earns or is charged daily interest, on which rate card, over what window. Append-only and effective-dated. One live enrolment per account, by EXCLUDE constraint.';


-- An enrolment is only meaningful on a customer deposit leaf. Written as
-- a trigger because a CHECK cannot subquery, and checked at ENROLMENT
-- rather than at every day: an account that is not a deposit leaf is a
-- mistake somebody made once, not a condition that changes nightly.
CREATE FUNCTION assert_interest_schedule() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_acct account%ROWTYPE;
BEGIN
  SELECT * INTO v_acct FROM account WHERE id = NEW.account_id;

  IF v_acct.code <> '2100' OR v_acct.business_id IS NULL THEN
    RAISE EXCEPTION
      'account % is %/% -- interest accrues on a customer deposit leaf (2100 with a business), nothing else',
      NEW.account_id, v_acct.code, COALESCE(v_acct.business_id::text, 'house')
      USING ERRCODE = '55006';
  END IF;

  IF v_acct.closed_at IS NOT NULL THEN
    RAISE EXCEPTION 'account % was closed at %; a closed account accrues nothing',
      NEW.account_id, v_acct.closed_at USING ERRCODE = '55006';
  END IF;

  IF v_acct.book::text <> 'financial' THEN
    RAISE EXCEPTION 'account % is in the % book; interest is real money',
      NEW.account_id, v_acct.book USING ERRCODE = '55006';
  END IF;

  -- An enrolment that starts before the rate card does would produce
  -- days with no resolvable rate, which would fail one at a time at the
  -- posting trigger instead of once, here, where it can be fixed.
  IF (interest_rate_at(NEW.rate_tier, NEW.start_date)).id IS NULL THEN
    RAISE EXCEPTION
      'rate card % has no row effective on or before %, so the first day of this enrolment could not be priced',
      NEW.rate_tier, NEW.start_date USING ERRCODE = '55006';
  END IF;

  RETURN NEW;
END $$;

ALTER FUNCTION assert_interest_schedule() SET search_path = public, pg_temp;

CREATE TRIGGER interest_schedule_shape
  BEFORE INSERT ON interest_schedule
  FOR EACH ROW EXECUTE FUNCTION assert_interest_schedule();


-- ---------------------------------------------------------------------
-- 12.  The claim -- at most once, by unique index
-- ---------------------------------------------------------------------
--
-- 0020 §9's construction, deliberately identical, because the
-- requirement is identical. The key is spelt `interest:` rather than
-- `accrual:` so that an interest day and a fee day for the same account
-- on the same date can never collide in journal_entry.idempotency_key --
-- and so that a human reading a key knows which product wrote it.

CREATE TABLE interest_day (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  schedule_id     uuid NOT NULL REFERENCES interest_schedule(id),

  -- THE BUSINESS DATE THIS IS INTEREST FOR. Not the date the job ran. It
  -- becomes the journal entry's value_date and the lifecycle trigger
  -- refuses any entry that says otherwise.
  accrual_date    date NOT NULL,

  -- Generated, from the two source facts and nothing else. The date is
  -- assembled from EXTRACTed integers rather than to_char(), because
  -- every textual rendering of a date is only STABLE (DateStyle is a
  -- session GUC) and a generated column's expression must be IMMUTABLE.
  -- A key that depends on a session setting is a key that silently
  -- becomes a different key, which is the exact shape of a double post.
  idempotency_key text GENERATED ALWAYS AS (
    'interest:' || schedule_id::text || ':'
      || lpad(EXTRACT(YEAR  FROM accrual_date)::int::text, 4, '0') || '-'
      || lpad(EXTRACT(MONTH FROM accrual_date)::int::text, 2, '0') || '-'
      || lpad(EXTRACT(DAY   FROM accrual_date)::int::text, 2, '0')
  ) STORED,

  claimed_at      timestamptz NOT NULL DEFAULT now(),
  claimed_by      text NOT NULL CHECK (length(btrim(claimed_by)) > 0),

  CONSTRAINT interest_day_once     UNIQUE (schedule_id, accrual_date),
  CONSTRAINT interest_day_key_once UNIQUE (idempotency_key)
);

CREATE INDEX interest_day_date_idx ON interest_day (accrual_date DESC, schedule_id);

COMMENT ON COLUMN interest_day.idempotency_key IS
  'GENERATED ALWAYS from the schedule and the date -- source facts, never a uuid the job made up. Handed to postEntry(), where journal_entry.idempotency_key is UNIQUE in turn.';


CREATE FUNCTION assert_interest_day() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_sched interest_schedule%ROWTYPE;
BEGIN
  SELECT * INTO v_sched FROM interest_schedule WHERE id = NEW.schedule_id;

  IF NEW.accrual_date < v_sched.start_date
     OR (v_sched.end_date IS NOT NULL AND NEW.accrual_date > v_sched.end_date) THEN
    RAISE EXCEPTION
      'enrolment % runs % .. %; % is outside it and can never accrue',
      NEW.schedule_id, v_sched.start_date,
      COALESCE(v_sched.end_date::text, 'open'), NEW.accrual_date
      USING ERRCODE = '55006';
  END IF;

  RETURN NEW;
END $$;

ALTER FUNCTION assert_interest_day() SET search_path = public, pg_temp;

CREATE TRIGGER interest_day_window
  BEFORE INSERT ON interest_day
  FOR EACH ROW EXECUTE FUNCTION assert_interest_day();


-- ---------------------------------------------------------------------
-- 13.  The outcome -- one per claimed day, with the whole sum shown
-- ---------------------------------------------------------------------
--
-- "A number a customer cannot reproduce by hand is a number they will
-- dispute." So the row carries the hand calculation and not just its
-- answer: the balance it was priced on, the watermark that balance was
-- read at, the rate, the day-count denominator, the exact fraction as
-- its two integers, the quotient, the remainder, which way it rounded,
-- and the cents posted.

CREATE TABLE interest_posting (
  interest_day_id      uuid PRIMARY KEY REFERENCES interest_day(id),
  disposition          accrual_disposition NOT NULL,   -- 0020's enum, reused

  -- ---- which side, and which rate card row priced it ----------------
  side                 interest_side NOT NULL,
  policy_id            uuid NOT NULL REFERENCES interest_rate_policy(id),

  -- ---- the basis, and the instant it was true at --------------------
  -- SIGNED: negative is an overdrawn customer. The magnitude goes into
  -- the arithmetic; the sign picks the side and therefore the accounts.
  basis_balance_cents  bigint NOT NULL,
  -- The booking watermark the balance was read at. WITHOUT THIS the
  -- figure is not reproducible: the settled balance of a past value date
  -- changes as later corrections are booked into it, so "the balance on
  -- 9 September" is only an answer once you say when you asked.
  observed_booking_seq bigint NOT NULL CHECK (observed_booking_seq >= 0),

  -- ---- the price of a day -------------------------------------------
  rate_bps             integer NOT NULL CHECK (rate_bps BETWEEN 0 AND 10000),
  day_count            integer NOT NULL CHECK (day_count IN (360, 365)),

  -- ---- the exact fraction, as the two integers it actually is -------
  numerator            bigint NOT NULL CHECK (numerator >= 0),
  denominator          bigint NOT NULL CHECK (denominator > 0),
  whole_cents          bigint NOT NULL CHECK (whole_cents >= 0),
  remainder_units      bigint NOT NULL CHECK (remainder_units >= 0),
  rounding             interest_rounding NOT NULL,

  -- The magnitude posted. The side says who pays whom.
  amount_cents         bigint NOT NULL CHECK (amount_cents >= 0),

  entry_id             uuid REFERENCES journal_entry(id),
  skip_reason          text,

  decided_at           timestamptz NOT NULL DEFAULT now(),
  decided_by_run       text NOT NULL CHECK (length(btrim(decided_by_run)) > 0),

  -- =================================================================
  -- THE ARITHMETIC, RE-DERIVED BY THE DATABASE ON EVERY INSERT.
  --
  -- Eight relations over four inputs (balance, rate, day count, and the
  -- sign of the balance). A row that disagrees with
  -- interest_round_half_even() by one cent cannot be stored, so the
  -- figures the screen renders are not a claim ABOUT the arithmetic --
  -- they ARE the arithmetic, checked by the thing that persisted them.
  --
  -- The last conjunct restates the rounding rule inline rather than
  -- delegating to the function a second time. It is deliberately
  -- redundant: if someone ever "optimises" interest_round_half_even into
  -- half-up, this line disagrees and no row can be written at all.
  -- =================================================================
  CONSTRAINT interest_posting_arithmetic CHECK (
        denominator     = interest_denominator(day_count)
    AND numerator       = interest_numerator(basis_balance_cents, rate_bps)
    AND whole_cents     = numerator / denominator
    AND remainder_units = numerator % denominator
    AND rounding        = interest_rounding_of(numerator, denominator)
    AND amount_cents    = interest_daily_cents(basis_balance_cents, rate_bps, day_count)
    AND side            = interest_side_of(basis_balance_cents)
    AND amount_cents    = whole_cents + CASE
                            WHEN 2 * remainder_units > denominator THEN 1
                            WHEN 2 * remainder_units < denominator THEN 0
                            ELSE whole_cents % 2
                          END
  ),

  -- A posted day has an entry, a non-zero amount and a real side; a
  -- skipped day has none of those and says why. There is no third shape.
  -- A 'flat' day -- a deposit account at exactly zero -- can only ever
  -- be skipped, which falls out of amount_cents = 0 rather than needing
  -- its own clause.
  CONSTRAINT interest_posting_shape CHECK (
       (disposition = 'posted'
          AND entry_id IS NOT NULL AND skip_reason IS NULL
          AND amount_cents > 0 AND side <> 'flat')
    OR (disposition = 'skipped'
          AND entry_id IS NULL AND skip_reason IS NOT NULL
          AND amount_cents = 0)
  )
);

CREATE INDEX interest_posting_entry_idx ON interest_posting (entry_id) WHERE entry_id IS NOT NULL;
CREATE INDEX interest_posting_side_idx  ON interest_posting (side);

COMMENT ON TABLE interest_posting IS
  'One decision per claimed day, by PRIMARY KEY. Carries the complete working -- balance, watermark, rate, day count, the exact fraction as two integers, the quotient, the remainder, the rounding direction and the cents -- so a customer can reproduce the number by hand from the row.';
COMMENT ON COLUMN interest_posting.observed_booking_seq IS
  'The booking watermark the basis balance was read at. The number is only reproducible with it: a backdated correction changes what the settled balance of a past value date is, and this says which answer was priced.';
COMMENT ON CONSTRAINT interest_posting_arithmetic ON interest_posting IS
  'Re-derives all eight relations from the balance, the rate and the day count, and restates the half-even tiebreak inline so that a change to the function alone cannot pass. TypeScript computes, Postgres verifies.';


-- The lifecycle gate. 0020 §10's instinct: the claims that would be
-- catastrophic if they were merely conventional.
CREATE FUNCTION assert_interest_posting() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  v_day      interest_day%ROWTYPE;
  v_sched    interest_schedule%ROWTYPE;
  v_policy   interest_rate_policy%ROWTYPE;
  v_entry    journal_entry%ROWTYPE;
  v_basis    bigint;
  v_expected integer;
  v_deposit  bigint;
  v_income   bigint;
  v_expense  bigint;
  v_lines    int;
BEGIN
  SELECT * INTO v_day   FROM interest_day      WHERE id = NEW.interest_day_id;
  SELECT * INTO v_sched FROM interest_schedule WHERE id = v_day.schedule_id;

  -- ---- the rate card row that priced it -----------------------------
  --
  -- THIS is "a rate change must not retroactively re-price yesterday",
  -- enforced at the moment the row is written. The policy is resolved
  -- from the tier and THE ACCRUAL DATE, so a replay of an old date
  -- resolves the old rate and a posting that cites any other row is
  -- refused.
  v_policy := interest_rate_at(v_sched.rate_tier, v_day.accrual_date);

  IF v_policy.id IS NULL THEN
    RAISE EXCEPTION 'rate card % has no row effective on or before %',
      v_sched.rate_tier, v_day.accrual_date USING ERRCODE = '55006';
  END IF;

  IF NEW.policy_id IS DISTINCT FROM v_policy.id THEN
    RAISE EXCEPTION
      'posting cites rate policy %, but % on % resolves to % (effective %)',
      NEW.policy_id, v_sched.rate_tier, v_day.accrual_date,
      v_policy.id, v_policy.effective_from USING ERRCODE = '42501';
  END IF;

  IF NEW.day_count IS DISTINCT FROM v_policy.day_count_denominator THEN
    RAISE EXCEPTION 'posting uses a /% day count but policy % is /%',
      NEW.day_count, v_policy.id, v_policy.day_count_denominator
      USING ERRCODE = '42501';
  END IF;

  v_expected := CASE NEW.side
                  WHEN 'credit'    THEN v_policy.credit_rate_bps
                  WHEN 'overdraft' THEN v_policy.overdraft_rate_bps
                  ELSE 0
                END;

  IF NEW.rate_bps IS DISTINCT FROM v_expected THEN
    RAISE EXCEPTION
      'posting prices the % side at % bps but policy % says % bps',
      NEW.side, NEW.rate_bps, v_policy.id, v_expected USING ERRCODE = '42501';
  END IF;

  -- ---- the basis, re-derived rather than believed --------------------
  --
  -- 0022's ledger_settled_cents IS the balance definition in this
  -- system. Asking it again here means the stored basis is a figure the
  -- database agrees with, not a figure the job asserted.
  v_basis := ledger_settled_cents(v_sched.account_id, v_day.accrual_date, NEW.observed_booking_seq);

  IF NEW.basis_balance_cents IS DISTINCT FROM v_basis THEN
    RAISE EXCEPTION
      'posting prices a balance of %c on % at watermark %, but the ledger says %c',
      NEW.basis_balance_cents, v_day.accrual_date, NEW.observed_booking_seq, v_basis
      USING ERRCODE = '42501';
  END IF;

  IF NEW.disposition::text = 'skipped' THEN
    RETURN NEW;
  END IF;

  -- ---- the journal entry IS this accrual -----------------------------
  SELECT * INTO v_entry FROM journal_entry WHERE id = NEW.entry_id;
  IF v_entry.id IS NULL THEN
    RAISE EXCEPTION 'posting for day % cites entry % which does not exist',
      NEW.interest_day_id, NEW.entry_id USING ERRCODE = '55006';
  END IF;

  -- The one that makes this exactly-once rather than merely careful.
  IF v_entry.idempotency_key IS DISTINCT FROM v_day.idempotency_key THEN
    RAISE EXCEPTION
      'day % derives key %, but entry % carries % -- these are not the same accrual',
      NEW.interest_day_id, v_day.idempotency_key, v_entry.id, v_entry.idempotency_key
      USING ERRCODE = '42501';
  END IF;

  -- VALUE DATE IS THE ACCRUAL DATE, NOT THE RUN DATE.
  IF v_entry.value_date IS DISTINCT FROM v_day.accrual_date THEN
    RAISE EXCEPTION
      'entry % has value date % but the interest is for % -- interest books at the date it accrued for',
      v_entry.id, v_entry.value_date, v_day.accrual_date USING ERRCODE = '42501';
  END IF;

  IF v_entry.book::text <> 'financial' THEN
    RAISE EXCEPTION 'entry % is in the % book; interest is real money',
      v_entry.id, v_entry.book USING ERRCODE = '42501';
  END IF;

  -- ---- and the entry must be the RIGHT SHAPE for its side ------------
  --
  -- credit    we PAY the customer:  deposit -amount (credit, we owe more)
  --                                 5400    +amount (debit, an expense)
  -- overdraft we CHARGE them:       deposit +amount (debit, we owe less)
  --                                 4400    -amount (credit, income)
  --
  -- Getting this backwards is the error chart.ts opens by warning about
  -- and the one that would show a customer their balance going UP every
  -- time we charged them overdraft interest.
  SELECT count(*),
         COALESCE(SUM(l.amount_cents) FILTER (WHERE l.account_id = v_sched.account_id), 0),
         COALESCE(SUM(l.amount_cents) FILTER (WHERE a.code = '4400'), 0),
         COALESCE(SUM(l.amount_cents) FILTER (WHERE a.code = '5400'), 0)
    INTO v_lines, v_deposit, v_income, v_expense
    FROM journal_line l JOIN account a ON a.id = l.account_id
   WHERE l.entry_id = v_entry.id;

  IF NEW.side = 'credit' THEN
    IF v_lines <> 2 OR v_deposit <> -NEW.amount_cents
       OR v_expense <> NEW.amount_cents OR v_income <> 0 THEN
      RAISE EXCEPTION
        'entry % is not this credit-interest accrual: % lines, %c to the deposit account, %c to 5400, %c to 4400; expected 2, %c, %c and 0',
        v_entry.id, v_lines, v_deposit, v_expense, v_income,
        -NEW.amount_cents, NEW.amount_cents USING ERRCODE = '42501';
    END IF;
  ELSE
    IF v_lines <> 2 OR v_deposit <> NEW.amount_cents
       OR v_income <> -NEW.amount_cents OR v_expense <> 0 THEN
      RAISE EXCEPTION
        'entry % is not this overdraft-interest accrual: % lines, %c to the deposit account, %c to 4400, %c to 5400; expected 2, %c, %c and 0',
        v_entry.id, v_lines, v_deposit, v_income, v_expense,
        NEW.amount_cents, -NEW.amount_cents USING ERRCODE = '42501';
    END IF;
  END IF;

  RETURN NEW;
END $$;

ALTER FUNCTION assert_interest_posting() SET search_path = public, pg_temp;

CREATE TRIGGER interest_posting_lifecycle
  BEFORE INSERT ON interest_posting
  FOR EACH ROW EXECUTE FUNCTION assert_interest_posting();


-- ---------------------------------------------------------------------
-- 14.  The row lock, without the UPDATE privilege
-- ---------------------------------------------------------------------
--
-- 0008's, 0012's and 0020's construction. corgi_app holds no UPDATE on
-- interest_schedule and must not, so it cannot write FOR UPDATE itself.
-- Taken in the CALLER's transaction, released at the caller's COMMIT.
--
-- It serialises two ticks that want the same enrolment. It is NOT what
-- makes the job exactly-once -- the unique indexes are -- and the
-- difference matters, because a crashed process releases a lock and
-- cannot release a unique index.

CREATE FUNCTION lock_interest_schedule(p_schedule uuid)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_id uuid;
BEGIN
  SELECT s.id INTO v_id FROM interest_schedule s WHERE s.id = p_schedule FOR UPDATE;
  RETURN v_id IS NOT NULL;
END $$;

ALTER FUNCTION lock_interest_schedule(uuid) SET search_path = public, pg_temp;
REVOKE ALL ON FUNCTION lock_interest_schedule(uuid) FROM PUBLIC;


-- ---------------------------------------------------------------------
-- 15.  What is owed: the calendar, in ONE place
-- ---------------------------------------------------------------------
--
-- 0012 §8 and 0020 §12's rule, applied again: no date arithmetic in
-- TypeScript. The set of dates an enrolment owes is a SQL function, the
-- tick asks it, and there is no second implementation of "which days are
-- in the window" to drift from this one.

CREATE FUNCTION interest_due_dates(p_schedule uuid, p_from date, p_to date)
RETURNS SETOF date
LANGUAGE sql STABLE AS $$
  SELECT d::date
    FROM interest_schedule s,
         generate_series(
           GREATEST(s.start_date, p_from)::timestamp,
           LEAST(COALESCE(s.end_date, p_to), p_to)::timestamp,
           interval '1 day'
         ) AS d
   WHERE s.id = p_schedule
     AND NOT EXISTS (
           SELECT 1 FROM interest_day id2
            WHERE id2.schedule_id = s.id AND id2.accrual_date = d::date
         )
   ORDER BY 1
$$;

ALTER FUNCTION interest_due_dates(uuid, date, date) SET search_path = public, pg_temp;

COMMENT ON FUNCTION interest_due_dates(uuid, date, date) IS
  'The only definition of which dates an interest enrolment still owes. The tick asks it; nothing in TypeScript computes a date range.';


-- ---------------------------------------------------------------------
-- 16.  The views, including the two that must always be empty
-- ---------------------------------------------------------------------

-- The screen's row source: one row per claimed day, decided or not, with
-- the whole working and the entry it cites.
CREATE VIEW v_interest_daily AS
SELECT d.id                    AS interest_day_id,
       d.schedule_id,
       s.account_id,
       a.business_id,
       b.legal_name            AS business_name,
       a.name                  AS account_name,
       s.rate_tier,
       d.accrual_date,
       d.idempotency_key,
       d.claimed_at,
       d.claimed_by,
       ip.disposition,
       ip.side,
       ip.policy_id,
       p.effective_from        AS policy_effective_from,
       ip.basis_balance_cents,
       ip.observed_booking_seq,
       ip.rate_bps,
       ip.day_count,
       ip.numerator,
       ip.denominator,
       ip.whole_cents,
       ip.remainder_units,
       ip.rounding,
       ip.amount_cents,
       -- The SIGNED effect on the customer's deposit account, which is
       -- the number they actually care about: negative is a debit.
       CASE ip.side
         WHEN 'credit'    THEN  ip.amount_cents
         WHEN 'overdraft' THEN -ip.amount_cents
         ELSE 0::bigint
       END                     AS customer_effect_cents,
       ip.entry_id,
       ip.skip_reason,
       ip.decided_at,
       ip.decided_by_run
  FROM interest_day d
  JOIN interest_schedule s ON s.id = d.schedule_id
  JOIN account a           ON a.id = s.account_id
  LEFT JOIN business b     ON b.id = a.business_id
  LEFT JOIN interest_posting ip ON ip.interest_day_id = d.id
  LEFT JOIN interest_rate_policy p ON p.id = ip.policy_id;

COMMENT ON VIEW v_interest_daily IS
  'One row per claimed interest day with the complete working: the balance, the watermark it was read at, the rate, the day count, the fraction as two integers, the rounding direction and the cents.';


-- One row per (enrolment, month): how many days, how much was paid, how
-- much was charged, and how many days each rounding direction took.
-- There is deliberately NO target column here and no month_drift view to
-- go with it -- daily interest has no monthly total to sum back to, and
-- inventing one would be pretending §12.3 applies.
CREATE VIEW v_interest_month AS
SELECT s.id                                                   AS schedule_id,
       s.account_id,
       a.business_id,
       s.rate_tier,
       date_trunc('month', d.accrual_date::timestamp)::date    AS month_start,
       count(*)                                               AS days_claimed,
       count(ip.*)                                            AS days_decided,
       count(*) FILTER (WHERE ip.disposition = 'posted')       AS days_posted,
       count(*) FILTER (WHERE ip.disposition = 'skipped')      AS days_skipped,
       count(*) FILTER (WHERE ip.side = 'credit')              AS days_credit,
       count(*) FILTER (WHERE ip.side = 'overdraft')           AS days_overdraft,
       count(*) FILTER (WHERE ip.rounding = 'up')              AS days_rounded_up,
       count(*) FILTER (WHERE ip.rounding = 'down')            AS days_rounded_down,
       count(*) FILTER (WHERE ip.rounding = 'tie_to_even')     AS days_tie_to_even,
       count(*) FILTER (WHERE ip.rounding = 'exact')           AS days_exact,
       COALESCE(SUM(ip.amount_cents) FILTER (WHERE ip.side = 'credit'), 0)
                                                              AS credit_interest_cents,
       COALESCE(SUM(ip.amount_cents) FILTER (WHERE ip.side = 'overdraft'), 0)
                                                              AS overdraft_interest_cents,
       min(ip.basis_balance_cents)                            AS min_basis_cents,
       max(ip.basis_balance_cents)                            AS max_basis_cents
  FROM interest_day d
  JOIN interest_schedule s ON s.id = d.schedule_id
  JOIN account a           ON a.id = s.account_id
  LEFT JOIN interest_posting ip ON ip.interest_day_id = d.id
 GROUP BY s.id, s.account_id, a.business_id, s.rate_tier,
          date_trunc('month', d.accrual_date::timestamp);


-- MUST BE EMPTY. A posting whose journal entry is not the entry that
-- posting describes: wrong value date, wrong amount on the customer's
-- account, or the wrong side of the chart.
--
-- The lifecycle trigger refuses all of this at insert, so a row here
-- means the trigger is gone -- or that somebody edited a money row,
-- which the privileges say they cannot. IT CAN FAIL: dropping
-- interest_posting_lifecycle and inserting a posting against an entry
-- with a different value date produces a row, which was checked against
-- this database inside a transaction that was rolled back.
CREATE VIEW v_interest_ledger_drift AS
SELECT ip.interest_day_id,
       d.accrual_date,
       d.idempotency_key,
       e.id             AS entry_id,
       e.value_date,
       ip.side,
       ip.amount_cents,
       COALESCE(SUM(l.amount_cents) FILTER (WHERE l.account_id = s.account_id), 0) AS deposit_cents,
       COALESCE(SUM(l.amount_cents) FILTER (WHERE a.code = '4400'), 0)             AS income_cents,
       COALESCE(SUM(l.amount_cents) FILTER (WHERE a.code = '5400'), 0)             AS expense_cents
  FROM interest_posting ip
  JOIN interest_day      d ON d.id = ip.interest_day_id
  JOIN interest_schedule s ON s.id = d.schedule_id
  JOIN journal_entry     e ON e.id = ip.entry_id
  JOIN journal_line      l ON l.entry_id = e.id
  JOIN account           a ON a.id = l.account_id
 WHERE ip.disposition = 'posted'
 GROUP BY ip.interest_day_id, d.accrual_date, d.idempotency_key,
          e.id, e.value_date, ip.side, ip.amount_cents, s.account_id
HAVING e.value_date <> d.accrual_date
    OR COALESCE(SUM(l.amount_cents) FILTER (WHERE l.account_id = s.account_id), 0)
         <> CASE ip.side WHEN 'overdraft' THEN ip.amount_cents ELSE -ip.amount_cents END
    OR COALESCE(SUM(l.amount_cents) FILTER (WHERE a.code = '4400'), 0)
         <> CASE ip.side WHEN 'overdraft' THEN -ip.amount_cents ELSE 0::bigint END
    OR COALESCE(SUM(l.amount_cents) FILTER (WHERE a.code = '5400'), 0)
         <> CASE ip.side WHEN 'credit'    THEN  ip.amount_cents ELSE 0::bigint END;

COMMENT ON VIEW v_interest_ledger_drift IS
  'Must be empty. The posting, its value date and the two lines of its journal entry must agree, on the correct side of the chart. assert_interest_posting() refuses otherwise at insert.';


-- MUST BE EMPTY. A posting whose rate is not what the rate card says
-- applied on its accrual date.
--
-- THIS IS "A RATE CHANGE MUST NOT RETROACTIVELY RE-PRICE YESTERDAY",
-- asked of the whole book at any moment. The forward-only trigger on
-- interest_rate_policy makes the offending INSERT impossible; this view
-- is what would catch it if that trigger were dropped, and it can fail:
-- disabling the trigger and inserting a backdated policy row makes every
-- posting on or after that date appear here. Checked against this
-- database, in a transaction that was rolled back.
CREATE VIEW v_interest_rate_drift AS
SELECT ip.interest_day_id,
       d.accrual_date,
       s.rate_tier,
       ip.policy_id       AS posted_policy_id,
       p.id               AS resolved_policy_id,
       p.effective_from   AS resolved_effective_from,
       ip.side,
       ip.rate_bps        AS posted_rate_bps,
       CASE ip.side
         WHEN 'credit'    THEN p.credit_rate_bps
         WHEN 'overdraft' THEN p.overdraft_rate_bps
         ELSE 0
       END                AS resolved_rate_bps,
       ip.day_count       AS posted_day_count,
       p.day_count_denominator AS resolved_day_count
  FROM interest_posting ip
  JOIN interest_day      d ON d.id = ip.interest_day_id
  JOIN interest_schedule s ON s.id = d.schedule_id
  LEFT JOIN LATERAL (SELECT * FROM interest_rate_at(s.rate_tier, d.accrual_date)) p ON true
 WHERE p.id IS NULL
    OR ip.policy_id <> p.id
    OR ip.day_count <> p.day_count_denominator
    OR ip.rate_bps <> CASE ip.side
                        WHEN 'credit'    THEN p.credit_rate_bps
                        WHEN 'overdraft' THEN p.overdraft_rate_bps
                        ELSE 0
                      END;

COMMENT ON VIEW v_interest_rate_drift IS
  'Must be empty. Every posting must still resolve to the rate card row that was effective on its accrual date. A row here means a policy was backdated and days already on the ledger have been re-priced underneath.';


-- Claimed and never decided: a tick took the day and did not finish.
-- Safe -- nothing posted -- but never invisible.
CREATE VIEW v_interest_unresolved AS
SELECT d.id AS interest_day_id, d.schedule_id, d.accrual_date,
       d.idempotency_key, d.claimed_at, d.claimed_by,
       s.account_id, s.rate_tier
  FROM interest_day d
  JOIN interest_schedule s ON s.id = d.schedule_id
  LEFT JOIN interest_posting ip ON ip.interest_day_id = d.id
 WHERE ip.interest_day_id IS NULL;


-- Days an enrolment owes that nothing has claimed, up to the BOOK day.
--
-- book_date(now()) and not CURRENT_DATE, which is 0023's correction to
-- v_accrual_gap learned the first time rather than the second:
-- CURRENT_DATE resolves against the session TimeZone (UTC on Neon), so
-- between 20:00 and midnight Eastern it is already on tomorrow and would
-- report every enrolment as owing a day that has not happened.
CREATE VIEW v_interest_gap AS
SELECT s.id AS schedule_id, s.account_id, s.rate_tier, d AS missing_date
  FROM interest_schedule s
  CROSS JOIN LATERAL interest_due_dates(
    s.id, s.start_date, LEAST(COALESCE(s.end_date, book_date(now())), book_date(now()))
  ) AS d;

COMMENT ON VIEW v_interest_gap IS
  'Dates an enrolment owes and nothing has claimed, bounded by the BOOK day. Persistently non-empty means the tick is not running.';


-- The rate card as a screen reads it: every version, with the window it
-- was (or is) in force for. `superseded_on` is the next version's
-- effective date, so "which rate applied on 9 September" is answerable
-- by eye and not only by the resolution function.
CREATE VIEW v_interest_rate_card AS
SELECT p.id,
       p.tier,
       t.description       AS tier_description,
       p.effective_from,
       LEAD(p.effective_from) OVER (PARTITION BY p.tier ORDER BY p.effective_from)
                           AS superseded_on,
       p.credit_rate_bps,
       p.overdraft_rate_bps,
       p.day_count_denominator,
       p.note,
       p.created_at,
       (SELECT count(*) FROM interest_posting ip WHERE ip.policy_id = p.id) AS days_priced
  FROM interest_rate_policy p
  JOIN interest_rate_tier t ON t.tier = p.tier;


-- ---------------------------------------------------------------------
-- 17.  Append-only, in two layers
-- ---------------------------------------------------------------------
--
-- No journal line is written by anything in this file -- postEntry()
-- does that -- so these are not money tables. They are the AUDIT of
-- money movement plus the policy it was priced by, and an audit trail
-- you can UPDATE is a story. 0012 §12 and 0020 §14's treatment,
-- unchanged: no UPDATE/DELETE grant, and 0001's ledger_row_is_immutable()
-- as the second layer that also binds the owner.
--
-- interest_rate_policy is in the list for the reason the rest of this
-- migration is about: a rate you can edit in place is a rate that can
-- re-price the past, and the whole of §5 is an argument that it must not
-- be able to.

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['interest_rate_tier', 'interest_rate_policy',
                           'interest_schedule', 'interest_day', 'interest_posting'] LOOP
    EXECUTE format(
      'CREATE TRIGGER %I_no_update_delete BEFORE UPDATE OR DELETE ON %I
         FOR EACH ROW EXECUTE FUNCTION ledger_row_is_immutable()', t, t);
    EXECUTE format(
      'CREATE TRIGGER %I_no_truncate BEFORE TRUNCATE ON %I
         FOR EACH STATEMENT EXECUTE FUNCTION ledger_row_is_immutable()', t, t);
  END LOOP;
END $$;

GRANT SELECT, INSERT ON
  interest_rate_tier, interest_rate_policy, interest_schedule,
  interest_day, interest_posting
TO corgi_app;

-- Explicit and redundant, so a reviewer can grep for it -- 0001's words.
REVOKE UPDATE, DELETE, TRUNCATE ON
  interest_rate_tier, interest_rate_policy, interest_schedule,
  interest_day, interest_posting
FROM corgi_app;

GRANT SELECT ON
  v_interest_daily, v_interest_month, v_interest_ledger_drift,
  v_interest_rate_drift, v_interest_unresolved, v_interest_gap,
  v_interest_rate_card
TO corgi_app;

GRANT EXECUTE ON FUNCTION
  interest_denominator(int),
  interest_numerator(bigint, int),
  interest_round_half_even(bigint, bigint),
  interest_rounding_of(bigint, bigint),
  interest_daily_cents(bigint, int, int),
  interest_side_of(bigint),
  interest_rate_at(text, date),
  interest_due_dates(uuid, date, date),
  lock_interest_schedule(uuid)
TO corgi_app;


-- ---------------------------------------------------------------------
-- 18.  The rate card, and the enrolments, for the accounts that exist
-- ---------------------------------------------------------------------
--
-- TWO POLICY VERSIONS, seeded in ascending order so the forward-only
-- trigger accepts both, because ONE version could not demonstrate the
-- thing §5 is about. With two, the same account on two adjacent business
-- dates is priced by two different rows, and re-running the earlier date
-- still resolves the earlier row.
--
--   v1   book_date - 4    credit 150 bps   overdraft 1800 bps   /365
--   v2   book_date - 2    credit 125 bps   overdraft 1800 bps   /365
--
-- THE CREDIT RATE IS CUT AND THE OVERDRAFT RATE IS NOT. That is the
-- realistic direction and it is also the one a customer notices, which
-- is the point of being able to prove that the cut did not reach back.
--
-- THE OVERDRAFT RATE IS ON THE CARD AND HAS PRICED NOTHING. No deposit
-- leaf on this book has been in debit on any value date -- measured, §1
-- -- so 4400 will carry a zero balance until one is. That is the honest
-- state of this feature and the screen says so on its face rather than
-- an overdraft being manufactured to photograph.
--
-- Dates are relative to the book day rather than hard-coded, so the same
-- shape appears whenever this migration is applied, including after a
-- db:reset. Idempotent by NOT EXISTS rather than by ON CONFLICT, so the
-- forward-only trigger never fires on a re-run at all.

INSERT INTO interest_rate_tier (tier, description)
VALUES ('standard',
        'The standard business current account rate card: what we pay on a credit balance and what we charge on an arranged overdraft, both ACT/365 fixed.')
ON CONFLICT (tier) DO NOTHING;

INSERT INTO interest_rate_policy
  (tier, effective_from, credit_rate_bps, overdraft_rate_bps, day_count_denominator, note, created_by)
SELECT 'standard',
       book_date(now()) - 4,
       150,
       1800,
       365,
       'Opening rate card. 1.50% a year on credit balances, 18.00% a year on an arranged overdraft, ACT/365 fixed per Reg DD Appendix A.',
       act.id
  FROM actor act
 WHERE act.kind = 'system' AND act.display_name = 'ledger-poster'
   AND NOT EXISTS (
         SELECT 1 FROM interest_rate_policy p
          WHERE p.tier = 'standard' AND p.effective_from = book_date(now()) - 4);

INSERT INTO interest_rate_policy
  (tier, effective_from, credit_rate_bps, overdraft_rate_bps, day_count_denominator, note, created_by)
SELECT 'standard',
       book_date(now()) - 2,
       125,
       1800,
       365,
       'Credit rate cut to 1.25% a year. The overdraft rate is unchanged. Days before this date keep the 1.50% card: interest_rate_at() resolves on the ACCRUAL date, and interest_rate_policy_forward_only would have refused this row if any day on or after it had already accrued.',
       act.id
  FROM actor act
 WHERE act.kind = 'system' AND act.display_name = 'ledger-poster'
   AND NOT EXISTS (
         SELECT 1 FROM interest_rate_policy p
          WHERE p.tier = 'standard' AND p.effective_from = book_date(now()) - 2);


-- Every open customer deposit leaf is enrolled. Interest is a property
-- of holding a balance, not of a plan somebody bought -- which is why
-- this is not the three-of-four the platform-fee schedules are.
--
-- start_date is book_date - 4, the same day the rate card opens, so the
-- first tick has five business dates to accrue and the rate change on
-- book_date - 2 falls inside them with days either side.
INSERT INTO interest_schedule
  (account_id, rate_tier, start_date, created_by, schedule_key)
SELECT a.id,
       'standard',
       book_date(now()) - 4,
       act.id,
       'migration:0024:' || a.id::text || ':interest'
  FROM account a
  JOIN actor act ON act.kind = 'system' AND act.display_name = 'ledger-poster'
 WHERE a.code = '2100'
   AND a.business_id IS NOT NULL
   AND a.closed_at IS NULL
ON CONFLICT (schedule_key) DO NOTHING;
