/**
 * The standing-orders screen's data contract.
 *
 * Same seam, and the same rules, as `src/components/recon/data-contract.ts`:
 * nothing under `src/components/**` opens a connection, imports `postgres`, or
 * reaches into `src/lib/standing/*` for anything but these types. The screen
 * depends on this interface; `src/lib/standing/screen.ts` implements it against
 * the live database and `./fixtures.ts` implements it without one.
 *
 * Shape notes:
 *
 * - **Every amount is integer minor units (US cents)**, never dollars, never a
 *   float. `number` rather than `bigint` because these cross the server/client
 *   boundary and `bigint` does not survive JSON; the query layer works in
 *   `bigint` throughout and narrows once, at the edge, in `screen.ts`.
 * - **Scheduled dates are `YYYY-MM-DD`**; instants are ISO 8601. They are
 *   different types because they are different clocks. A standing order is due
 *   on a DATE — that is what a mandate says — and the occurrence's identity is
 *   built from that date, not from the instant a cron happened to fire.
 * - **Failure is a value, not a throw**, so the error state is a branch.
 * - **The screen never writes.** Firing is an operator or cron action with a
 *   run id attached; a render is not one, and a page that fired a payment
 *   because somebody refreshed it would be the worst bug in this repository.
 */

import type { ErrorShape, Result } from "@/lib/result";
import type {
  StandingOrderCadence,
  StandingOrderDisposition,
} from "@/lib/standing/types";

/** Integer minor units (US cents). Never dollars. */
export type Cents = number;
/** ISO 8601 instant. */
export type Instant = string;
/** `YYYY-MM-DD`. The scheduled-date axis, not an instant. */
export type ScheduledDate = string;

export type { StandingOrderCadence, StandingOrderDisposition };

/* -------------------------------------------------------------------------- */
/* A mandate                                                                  */
/* -------------------------------------------------------------------------- */

export type ScheduleRow = {
  readonly id: string;
  readonly reference: string;
  readonly accountId: string;
  readonly accountName: string;
  readonly businessName: string | null;
  readonly rail: string;
  readonly amountCents: Cents;
  readonly currency: string;
  /** One line an operator can check a payee against. Never a full account number. */
  readonly destination: string;
  readonly cadence: StandingOrderCadence;
  /** Plain English: "monthly on the 1st", "weekly on Friday". */
  readonly cadenceLabel: string;
  readonly startDate: ScheduledDate;
  readonly endDate: ScheduledDate | null;
  /** Derived from the fact that created the mandate. UNIQUE in the database. */
  readonly mandateKey: string;
  readonly createdByName: string;
  readonly createdAt: Instant;
  readonly cancelled: boolean;
  readonly cancelledAt: Instant | null;
  readonly cancellationReason: string | null;
  /**
   * The next date the schedule generates that has NOT been claimed. `null`
   * once the mandate has run out of dates, or once it is cancelled.
   */
  readonly nextDueDate: ScheduledDate | null;
};

/* -------------------------------------------------------------------------- */
/* An occurrence                                                              */
/* -------------------------------------------------------------------------- */

/**
 * One (standing order, scheduled date) pair, and what happened to it.
 *
 * `disposition === null` is not an error state and not a pending flag: it is a
 * claim with no outcome row, which means a process took the occurrence and did
 * not finish. Nothing moved. The next tick re-drives it to the same instruction
 * through the same derived key. The screen shows it, loudly, because the
 * failure mode the requirement names — "it never fired and nobody knows why" —
 * is a MISSING row, and the cure is that the claim is a presence rather than an
 * absence somebody has to notice.
 */
export type OccurrenceRow = {
  readonly occurrenceId: string;
  readonly standingOrderId: string;
  readonly reference: string;
  readonly scheduledDate: ScheduledDate;
  /** `standing:<order id>:<YYYY-MM-DD>` — generated by Postgres, not by us. */
  readonly idempotencyKey: string;
  readonly claimedAt: Instant;
  readonly claimedBy: string;
  readonly amountCents: Cents;
  readonly currency: string;
  readonly rail: string;

  readonly disposition: StandingOrderDisposition | null;
  /** Set on `raised`. The payment instruction this occurrence put in the queue. */
  readonly instructionId: string | null;
  readonly refusalCode: string | null;
  readonly refusalReason: string | null;

  /* ---- what was true at the moment of the decision ---- */
  readonly observedLedgerCents: Cents | null;
  readonly observedHoldsCents: Cents | null;
  readonly observedUnclearedCents: Cents | null;
  readonly observedAvailableCents: Cents | null;
  readonly shortfallCents: Cents | null;

  /**
   * True when the occurrence was refused for funds AND the ledger balance on
   * its own would have covered it.
   *
   * This is the whole point of the track rendered as a boolean: the money was
   * in the ledger and was still not spendable, because it was committed to a
   * card authorisation or sitting in a credit that had not cleared. Derived on
   * the server from the observed figures so no component re-derives it.
   */
  readonly ledgerWouldHaveCovered: boolean;

  readonly decidedAt: Instant | null;
  readonly decidedByRun: string | null;
};

/* -------------------------------------------------------------------------- */
/* Invariants                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * The two questions migration 0012 §14 says the database can be asked at any
 * moment, asked on every render.
 *
 * They are on the screen rather than in a test because a test proves a thing
 * once and a screen proves it while somebody is watching.
 */
export type StandingInvariants = {
  /** Claimed, never decided. Safe — nothing moved — but never invisible. */
  readonly unresolved: number;
  /**
   * Occurrences whose derived key names more than one payment instruction.
   *
   * Structurally impossible: `payment_instruction.idempotency_key` is UNIQUE.
   * Non-zero here would mean that index is gone.
   */
  readonly doubleFires: number;
};

/* -------------------------------------------------------------------------- */
/* The view                                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Where the numbers came from. Rendered on the screen, always — a figure
 * without provenance is a rumour.
 */
export type StandingSource = "live" | "fixture";

export type StandingView = {
  readonly source: StandingSource;
  /** The instant the read was taken. Every age on screen is measured to this. */
  readonly asOf: Instant;
  /** Today in book time (America/New_York), as the database answers it. */
  readonly bookDate: ScheduledDate;
  readonly schedules: readonly ScheduleRow[];
  /** Newest scheduled date first. Every occurrence, decided or not. */
  readonly occurrences: readonly OccurrenceRow[];
  readonly invariants: StandingInvariants;
  /** Present when an occurrence is selected in the URL. */
  readonly selected: OccurrenceRow | null;
};

export type StandingQuery = {
  /** Show only this mandate's occurrences. Omit for all of them. */
  readonly standingOrderId?: string | undefined;
  /** Drill into one occurrence. */
  readonly occurrenceId?: string | undefined;
};

export interface StandingDataSource {
  load(query: StandingQuery): Promise<Result<StandingView, ErrorShape>>;
}

/* -------------------------------------------------------------------------- */
/* What the authorise / stop forms need                                       */
/* -------------------------------------------------------------------------- */

/**
 * One account a mandate may be paid from.
 *
 * The currency is carried because it is the ACCOUNT's, not the form's: a
 * mandate is written in the currency of the account it debits, so the form
 * shows it rather than offering it as a choice somebody could get wrong.
 *
 * This list is a convenience, not a control. `createStandingOrderAction`
 * re-reads the same accounts and refuses an id that is not among them.
 */
export type MandateAccountOption = {
  readonly accountId: string;
  readonly legalName: string;
  readonly accountName: string;
  readonly currency: string;
};

/** One live mandate, as the stop form lists it. */
export type CancellableMandate = {
  readonly id: string;
  readonly reference: string;
  readonly cadence: string;
  readonly nextDueDate: string | null;
};
