/**
 * The standing-order vocabulary, and the two decisions that are pure.
 *
 * Nothing in this file talks to a database. The exactly-once guarantee lives
 * in `db/migrations/0012_standing_orders.sql` — a UNIQUE constraint on
 * (standing order, scheduled date), a generated idempotency key, and a trigger
 * that refuses an outcome citing the wrong instruction. These are the types the
 * application uses to *talk about* that, plus the funding and freshness rules,
 * which are pure functions of numbers and dates and are unit-tested as such.
 *
 * Money is `bigint` minor units throughout. There is no `number` cents anywhere
 * below this line except in the screen's data contract, where the narrowing
 * happens once, in `screen.ts`.
 */

import type { z } from "zod";

import { destinationSchema, type PayoutRail } from "@/lib/approvals/types";

/* -------------------------------------------------------------------------- */
/* Schedules                                                                  */
/* -------------------------------------------------------------------------- */

export const STANDING_ORDER_CADENCES = ["daily", "weekly", "monthly"] as const;

export type StandingOrderCadence = (typeof STANDING_ORDER_CADENCES)[number];

export const STANDING_ORDER_DISPOSITIONS = ["raised", "refused"] as const;

export type StandingOrderDisposition = (typeof STANDING_ORDER_DISPOSITIONS)[number];

/**
 * What the firing routine did with one occurrence.
 *
 * `deferred` is NOT a disposition the database stores. It is this run's report
 * that the occurrence was left undecided on purpose — no outcome row was
 * written, so it is still open, it shows in `v_standing_order_unresolved`, and
 * the next run picks it up. See `DEFERRABLE_CODES`.
 */
export type OccurrenceAction = StandingOrderDisposition | "deferred";

/** Same jsonb shape as `payment_instruction.counterparty`, and the same schema. */
export const standingOrderDestinationSchema = destinationSchema;

export type StandingOrderDestination = z.infer<typeof standingOrderDestinationSchema>;

export type StandingOrder = {
  readonly id: string;
  readonly reference: string;
  readonly accountId: string;
  readonly accountName: string;
  readonly businessId: string | null;
  readonly businessName: string | null;
  readonly rail: PayoutRail;
  readonly amountCents: bigint;
  readonly currency: string;
  readonly destination: StandingOrderDestination | null;
  readonly cadence: StandingOrderCadence;
  readonly dayOfMonth: number | null;
  readonly dayOfWeek: number | null;
  readonly startDate: string;
  readonly endDate: string | null;
  readonly mandateKey: string;
  readonly createdAt: string;
  readonly createdByActorId: string;
  readonly createdByName: string;
  readonly cancelled: boolean;
  readonly cancelledAt: string | null;
  readonly cancellationReason: string | null;
  /** From `v_standing_order_next`. Null once the mandate has run out of dates. */
  readonly nextDueDate: string | null;
};

export type StandingOrderOccurrence = {
  readonly occurrenceId: string;
  readonly standingOrderId: string;
  readonly reference: string;
  readonly scheduledDate: string;
  /** `standing:<order id>:<YYYY-MM-DD>`, generated by Postgres. */
  readonly idempotencyKey: string;
  readonly claimedAt: string;
  readonly claimedBy: string;
  readonly amountCents: bigint;
  readonly currency: string;
  readonly rail: PayoutRail;
  /** Null while the occurrence is claimed but undecided. */
  readonly disposition: StandingOrderDisposition | null;
  readonly instructionId: string | null;
  readonly refusalCode: string | null;
  readonly refusalReason: string | null;
  readonly observedLedgerCents: bigint | null;
  readonly observedHoldsCents: bigint | null;
  readonly observedUnclearedCents: bigint | null;
  readonly observedAvailableCents: bigint | null;
  readonly shortfallCents: bigint | null;
  readonly decidedAt: string | null;
  readonly decidedByRun: string | null;
};

/* -------------------------------------------------------------------------- */
/* The funding rule                                                           */
/* -------------------------------------------------------------------------- */

/**
 * The four figures the decision is made against, as `availableBalance()`
 * returns them.
 *
 * WHICH NUMBER THE RULE USES, AND WHY IT IS NOT THE LEDGER BALANCE.
 *
 * `available = ledger − active holds − uncleared credits`. A standing order is
 * checked against AVAILABLE, and the difference is the entire point of the
 * track:
 *
 *   - An active card authorisation is money the customer has already committed.
 *     A $50 fuel-pump hold that has not settled is not spendable, even though
 *     no journal line has moved it yet. Paying rent out of it creates an
 *     overdraft the customer never agreed to, on the day the pump captures.
 *   - An uncleared credit is money that can still be taken back. ACH gives the
 *     originator days to return it. Standing orders leave on rails that are
 *     slower to recall than the credit is, so funding one from an uncleared
 *     deposit is lending, and this is a current account, not a credit facility.
 *
 * The refusal records both figures, so the screen can show the case where the
 * LEDGER was sufficient and AVAILABLE was not — which is the only interesting
 * insufficient-funds refusal there is.
 */
export type AvailabilitySnapshot = {
  readonly ledgerCents: bigint;
  readonly holdsCents: bigint;
  readonly unclearedCents: bigint;
  readonly availableCents: bigint;
};

export const INSUFFICIENT_FUNDS_CODE = "INSUFFICIENT_AVAILABLE_FUNDS";
export const STALE_OCCURRENCE_CODE = "STALE_OCCURRENCE";
export const INVALID_DESTINATION_CODE = "INVALID_DESTINATION";
/**
 * The mandate's account belongs to no business, so there is no availability to
 * check it against.
 *
 * `availableBalance()` is scoped to a business, because holds are reached
 * through the deposit account and uncleared credits through the same. The
 * platform's own 2100 leaf has `business_id IS NULL`; a mandate pointed at it
 * has no customer whose available balance could cover it. Refused rather than
 * defaulted to zero — a payment that cannot be funds-checked must not be
 * raised, and a payment that was refused for a reason nobody can name is the
 * failure mode this whole table exists to prevent.
 */
export const UNSCOPED_ACCOUNT_CODE = "UNSCOPED_ACCOUNT";

export type FundingDecision =
  | { readonly kind: "fund" }
  | {
      readonly kind: "refuse";
      readonly code: typeof INSUFFICIENT_FUNDS_CODE;
      readonly reason: string;
      readonly shortfallCents: bigint;
    };

/**
 * THE POLICY, in five lines of code and one paragraph of prose.
 *
 * If available covers the amount, fund it. If it does not, REFUSE THIS
 * OCCURRENCE AND CLOSE IT: no partial payment, no carry-forward to tomorrow, no
 * queue that fires whenever the money happens to arrive. The next occurrence is
 * unaffected and fires on its own date.
 *
 * The full argument, including what was rejected and why, is in
 * docs/STANDING-ORDERS.md. The short version:
 *
 *   - A partial payment invents an instruction nobody authorised. A mandate
 *     says "$4,000 on the 1st"; $2,613.44 is a different payment, it will not
 *     match the payee's invoice, and it converts a clean failure into a
 *     reconciliation break at both ends.
 *   - Carrying forward makes the debit arrive on a day nobody chose, at a size
 *     nobody expected, possibly doubled up against the next scheduled one. That
 *     is the 3am surprise the requirement warns about, and it is unbounded.
 *   - So the occurrence is closed as attempted-and-refused, with the reason and
 *     the four observed figures on the row. It did not silently vanish; it is
 *     on the screen with a shortfall in dollars.
 */
export function decideFunding(
  amountCents: bigint,
  availability: AvailabilitySnapshot,
): FundingDecision {
  if (availability.availableCents >= amountCents) return { kind: "fund" };

  const shortfall = amountCents - availability.availableCents;
  const ledgerWouldHaveCovered = availability.ledgerCents >= amountCents;

  return {
    kind: "refuse",
    code: INSUFFICIENT_FUNDS_CODE,
    shortfallCents: shortfall,
    reason: ledgerWouldHaveCovered
      ? "Refused: the ledger balance covers this payment but the available balance does not. " +
        "The difference is money already committed to card authorisations or to credits that have " +
        "not cleared, and neither is spendable. This occurrence is closed; the next one is unaffected."
      : "Refused: the available balance does not cover this payment. " +
        "This occurrence is closed and is not carried forward; the next one is unaffected.",
  };
}

/* -------------------------------------------------------------------------- */
/* The freshness rule                                                         */
/* -------------------------------------------------------------------------- */

/**
 * How many book days late an occurrence may be and still fire.
 *
 * This exists because the catch-up path is the other way a standing order can
 * surprise somebody. If the scheduler is down for a fortnight, waking up and
 * firing fourteen days of rent in one batch is worse than not firing at all —
 * and unlike an insufficient-funds refusal, it moves money.
 *
 * Five days: long enough that a weekend plus a bank holiday plus a bad deploy
 * does not silently drop a payment, short enough that anything older is a
 * conversation rather than an automatic debit.
 */
export const STALE_AFTER_DAYS = 5;

/**
 * How far back the firing routine will look for dates it has never claimed.
 *
 * Wider than STALE_AFTER_DAYS on purpose. Everything between the two windows is
 * still claimed and still recorded — as `refused / STALE_OCCURRENCE` — because
 * the failure mode that hurts is a missing row, not a refusal. Past 45 days a
 * date that was never claimed is not materialised at all, and that limit is
 * stated in docs/STANDING-ORDERS.md rather than left to be discovered.
 */
export const CATCH_UP_WINDOW_DAYS = 45;

export type FreshnessDecision =
  | { readonly kind: "fresh" }
  | {
      readonly kind: "refuse";
      readonly code: typeof STALE_OCCURRENCE_CODE;
      readonly reason: string;
      readonly daysLate: number;
    };

/** Whole days between two `YYYY-MM-DD` dates. Calendar dates, never instants. */
export function daysBetweenDates(from: string, to: string): number {
  const a = Date.parse(`${from}T00:00:00Z`);
  const b = Date.parse(`${to}T00:00:00Z`);
  if (Number.isNaN(a) || Number.isNaN(b)) {
    throw new TypeError(`standing orders: expected YYYY-MM-DD, received ${from} / ${to}`);
  }
  return Math.round((b - a) / 86_400_000);
}

export function decideFreshness(scheduledDate: string, bookToday: string): FreshnessDecision {
  const daysLate = daysBetweenDates(scheduledDate, bookToday);
  if (daysLate <= STALE_AFTER_DAYS) return { kind: "fresh" };
  return {
    kind: "refuse",
    code: STALE_OCCURRENCE_CODE,
    daysLate,
    reason:
      `Refused: this occurrence was due on ${scheduledDate}, ${daysLate} days ago, and is past the ` +
      `${STALE_AFTER_DAYS}-day catch-up limit. A scheduled payment that nobody noticed was missing ` +
      `is not debited unannounced once the scheduler comes back; it is recorded here and raised by ` +
      `hand if it is still wanted.`,
  };
}

/* -------------------------------------------------------------------------- */
/* What a run reports                                                         */
/* -------------------------------------------------------------------------- */

/**
 * `requestPayment()` failure codes that must NOT close the occurrence.
 *
 * Both are operator problems rather than facts about this payment: a rail with
 * no approval policy in force is a row nobody wrote, and `UNAVAILABLE` is the
 * database being unreachable. Recording either as a refusal would permanently
 * kill a payment because of a transient condition, so the occurrence is left
 * undecided — visible in `v_standing_order_unresolved` — and re-driven next
 * run, where the derived idempotency key makes the retry safe.
 */
export const DEFERRABLE_CODES: ReadonlySet<string> = new Set(["UNAVAILABLE", "POLICY_MISSING"]);

export type OccurrenceReport = {
  readonly standingOrderId: string;
  readonly reference: string;
  readonly scheduledDate: string;
  readonly occurrenceId: string;
  readonly idempotencyKey: string;
  /** True when THIS run inserted the occurrence row; false when it recovered one. */
  readonly claimedNow: boolean;
  readonly action: OccurrenceAction;
  readonly instructionId: string | null;
  /**
   * True when the instruction already existed under this occurrence's derived
   * key, so this run raised nothing and recorded what Postgres already held.
   */
  readonly replayed: boolean;
  readonly code: string | null;
  readonly reason: string | null;
  readonly amountCents: bigint;
  readonly availability: AvailabilitySnapshot | null;
};

export type StandingRunResult = {
  readonly runId: string;
  readonly asOf: string;
  readonly bookDate: string;
  readonly considered: number;
  readonly raised: number;
  readonly refused: number;
  readonly deferred: number;
  readonly occurrences: readonly OccurrenceReport[];
  readonly durationMs: number;
};
